"""Curated dataset seed for training mode in MapTap."""

from typing import List
from utils.schemas import CityItem

CITIES_SEED: List[CityItem] = [
    # --- BRASIL: 27 Capitais ---
    CityItem(
        id="br-brasilia",
        name="Brasília",
        country="Brasil",
        country_code="BRA",
        state="Distrito Federal",
        state_code="DF",
        lat=-15.7975,
        lng=-47.8919,
        population=3055149,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="br-sao-paulo",
        name="São Paulo",
        country="Brasil",
        country_code="BRA",
        state="São Paulo",
        state_code="SP",
        lat=-23.5505,
        lng=-46.6333,
        population=12325232,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-rio-de-janeiro",
        name="Rio de Janeiro",
        country="Brasil",
        country_code="BRA",
        state="Rio de Janeiro",
        state_code="RJ",
        lat=-22.9068,
        lng=-43.1729,
        population=6747815,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-salvador",
        name="Salvador",
        country="Brasil",
        country_code="BRA",
        state="Bahia",
        state_code="BA",
        lat=-12.9777,
        lng=-38.5016,
        population=2886698,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-fortaleza",
        name="Fortaleza",
        country="Brasil",
        country_code="BRA",
        state="Ceará",
        state_code="CE",
        lat=-3.7319,
        lng=-38.5267,
        population=2686612,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-belo-horizonte",
        name="Belo Horizonte",
        country="Brasil",
        country_code="BRA",
        state="Minas Gerais",
        state_code="MG",
        lat=-19.9245,
        lng=-43.9352,
        population=2521564,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-manaus",
        name="Manaus",
        country="Brasil",
        country_code="BRA",
        state="Amazonas",
        state_code="AM",
        lat=-3.1190,
        lng=-60.0217,
        population=2219580,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-curitiba",
        name="Curitiba",
        country="Brasil",
        country_code="BRA",
        state="Paraná",
        state_code="PR",
        lat=-25.4284,
        lng=-49.2733,
        population=1948626,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-recife",
        name="Recife",
        country="Brasil",
        country_code="BRA",
        state="Pernambuco",
        state_code="PE",
        lat=-8.0476,
        lng=-34.8770,
        population=1653461,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-goiania",
        name="Goiânia",
        country="Brasil",
        country_code="BRA",
        state="Goiás",
        state_code="GO",
        lat=-16.6869,
        lng=-49.2648,
        population=1536097,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-belem",
        name="Belém",
        country="Brasil",
        country_code="BRA",
        state="Pará",
        state_code="PA",
        lat=-1.4558,
        lng=-48.4902,
        population=1499641,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-porto-alegre",
        name="Porto Alegre",
        country="Brasil",
        country_code="BRA",
        state="Rio Grande do Sul",
        state_code="RS",
        lat=-30.0346,
        lng=-51.2177,
        population=1488252,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-sao-luis",
        name="São Luís",
        country="Brasil",
        country_code="BRA",
        state="Maranhão",
        state_code="MA",
        lat=-2.5307,
        lng=-44.3068,
        population=1108975,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-maceio",
        name="Maceió",
        country="Brasil",
        country_code="BRA",
        state="Alagoas",
        state_code="AL",
        lat=-9.6658,
        lng=-35.7351,
        population=1025360,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-campo-grande",
        name="Campo Grande",
        country="Brasil",
        country_code="BRA",
        state="Mato Grosso do Sul",
        state_code="MS",
        lat=-20.4697,
        lng=-54.6201,
        population=906092,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-natal",
        name="Natal",
        country="Brasil",
        country_code="BRA",
        state="Rio Grande do Norte",
        state_code="RN",
        lat=-5.7945,
        lng=-35.2110,
        population=890480,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-teresina",
        name="Teresina",
        country="Brasil",
        country_code="BRA",
        state="Piauí",
        state_code="PI",
        lat=-5.0920,
        lng=-42.8038,
        population=868075,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-joao-pessoa",
        name="João Pessoa",
        country="Brasil",
        country_code="BRA",
        state="Paraíba",
        state_code="PB",
        lat=-7.1153,
        lng=-34.8610,
        population=817511,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-aracaju",
        name="Aracaju",
        country="Brasil",
        country_code="BRA",
        state="Sergipe",
        state_code="SE",
        lat=-10.9472,
        lng=-37.0731,
        population=664908,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-cuiaba",
        name="Cuiabá",
        country="Brasil",
        country_code="BRA",
        state="Mato Grosso",
        state_code="MT",
        lat=-15.6014,
        lng=-56.0979,
        population=618124,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-porto-velho",
        name="Porto Velho",
        country="Brasil",
        country_code="BRA",
        state="Rondônia",
        state_code="RO",
        lat=-8.7619,
        lng=-63.9039,
        population=539354,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-florianopolis",
        name="Florianópolis",
        country="Brasil",
        country_code="BRA",
        state="Santa Catarina",
        state_code="SC",
        lat=-27.5954,
        lng=-48.5480,
        population=508826,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-macapa",
        name="Macapá",
        country="Brasil",
        country_code="BRA",
        state="Amapá",
        state_code="AP",
        lat=0.0389,
        lng=-51.0694,
        population=512902,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-rio-branco",
        name="Rio Branco",
        country="Brasil",
        country_code="BRA",
        state="Acre",
        state_code="AC",
        lat=-9.9754,
        lng=-67.8249,
        population=413447,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-vitoria",
        name="Vitória",
        country="Brasil",
        country_code="BRA",
        state="Espírito Santo",
        state_code="ES",
        lat=-20.3155,
        lng=-40.3128,
        population=365855,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-boa-vista",
        name="Boa Vista",
        country="Brasil",
        country_code="BRA",
        state="Roraima",
        state_code="RR",
        lat=2.8235,
        lng=-60.6758,
        population=419652,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-palmas",
        name="Palmas",
        country="Brasil",
        country_code="BRA",
        state="Tocantins",
        state_code="TO",
        lat=-10.2491,
        lng=-48.3243,
        population=306296,
        is_capital=False,
        continent="América do Sul",
    ),

    # --- BRASIL: Cidades Relevantes do Interior / Litoral ---
    CityItem(
        id="br-campinas",
        name="Campinas",
        country="Brasil",
        country_code="BRA",
        state="São Paulo",
        state_code="SP",
        lat=-22.9099,
        lng=-47.0626,
        population=1213792,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-santos",
        name="Santos",
        country="Brasil",
        country_code="BRA",
        state="São Paulo",
        state_code="SP",
        lat=-23.9608,
        lng=-46.3336,
        population=433656,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-ribeirao-preto",
        name="Ribeirão Preto",
        country="Brasil",
        country_code="BRA",
        state="São Paulo",
        state_code="SP",
        lat=-21.1767,
        lng=-47.8108,
        population=711825,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-londrina",
        name="Londrina",
        country="Brasil",
        country_code="BRA",
        state="Paraná",
        state_code="PR",
        lat=-23.3045,
        lng=-51.1696,
        population=575377,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-joinville",
        name="Joinville",
        country="Brasil",
        country_code="BRA",
        state="Santa Catarina",
        state_code="SC",
        lat=-26.3045,
        lng=-48.8487,
        population=597658,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="br-foz-do-iguacu",
        name="Foz do Iguaçu",
        country="Brasil",
        country_code="BRA",
        state="Paraná",
        state_code="PR",
        lat=-25.5163,
        lng=-54.5854,
        population=258248,
        is_capital=False,
        continent="América do Sul",
    ),

    # --- MUNDO: Capitais e Metrópoles Globais ---
    CityItem(
        id="us-new-york",
        name="New York",
        country="Estados Unidos",
        country_code="USA",
        state="New York",
        state_code="NY",
        lat=40.7128,
        lng=-74.0060,
        population=8804190,
        is_capital=False,
        continent="América do Norte",
    ),
    CityItem(
        id="us-washington",
        name="Washington D.C.",
        country="Estados Unidos",
        country_code="USA",
        state="District of Columbia",
        state_code="DC",
        lat=38.9072,
        lng=-77.0369,
        population=689545,
        is_capital=True,
        continent="América do Norte",
    ),
    CityItem(
        id="us-los-angeles",
        name="Los Angeles",
        country="Estados Unidos",
        country_code="USA",
        state="California",
        state_code="CA",
        lat=34.0522,
        lng=-118.2437,
        population=3898747,
        is_capital=False,
        continent="América do Norte",
    ),
    CityItem(
        id="ar-buenos-aires",
        name="Buenos Aires",
        country="Argentina",
        country_code="ARG",
        state="Buenos Aires",
        state_code="BA",
        lat=-34.6037,
        lng=-58.3816,
        population=3120612,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="ar-cordoba",
        name="Córdoba",
        country="Argentina",
        country_code="ARG",
        state="Córdoba",
        state_code="CB",
        lat=-31.4201,
        lng=-64.1888,
        population=1391000,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="ar-rosario",
        name="Rosário",
        country="Argentina",
        country_code="ARG",
        state="Santa Fe",
        state_code="SF",
        lat=-32.9587,
        lng=-60.6930,
        population=1193605,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="ar-mendoza",
        name="Mendoza",
        country="Argentina",
        country_code="ARG",
        state="Mendoza",
        state_code="MZ",
        lat=-32.8895,
        lng=-68.8458,
        population=115041,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="cl-santiago",
        name="Santiago",
        country="Chile",
        country_code="CHL",
        state="Región Metropolitana",
        state_code="RM",
        lat=-33.4489,
        lng=-70.6693,
        population=6257516,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="cl-valparaiso",
        name="Valparaíso",
        country="Chile",
        country_code="CHL",
        state="Valparaíso",
        state_code="VS",
        lat=-33.0472,
        lng=-71.6127,
        population=296655,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="cl-concepcion",
        name="Concepción",
        country="Chile",
        country_code="CHL",
        state="Biobío",
        state_code="BI",
        lat=-36.8270,
        lng=-73.0503,
        population=223574,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="cl-antofagasta",
        name="Antofagasta",
        country="Chile",
        country_code="CHL",
        state="Antofagasta",
        state_code="AN",
        lat=-23.6509,
        lng=-70.3975,
        population=361115,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="cl-laserena",
        name="La Serena",
        country="Chile",
        country_code="CHL",
        state="Coquimbo",
        state_code="CO",
        lat=-29.9027,
        lng=-71.2520,
        population=221054,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="fr-paris",
        name="Paris",
        country="França",
        country_code="FRA",
        state="Île-de-France",
        state_code="IDF",
        lat=48.8566,
        lng=2.3522,
        population=2161000,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="gb-london",
        name="London",
        country="Reino Unido",
        country_code="GBR",
        state="England",
        state_code="ENG",
        lat=51.5074,
        lng=-0.1278,
        population=8982000,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="jp-tokyo",
        name="Tokyo",
        country="Japão",
        country_code="JPN",
        state="Kanto",
        state_code="13",
        lat=35.6762,
        lng=139.6503,
        population=13960000,
        is_capital=True,
        continent="Ásia",
    ),
    CityItem(
        id="de-berlin",
        name="Berlin",
        country="Alemanha",
        country_code="DEU",
        state="Berlin",
        state_code="BE",
        lat=52.5200,
        lng=13.4050,
        population=3645000,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="it-rome",
        name="Roma",
        country="Itália",
        country_code="ITA",
        state="Lazio",
        state_code="62",
        lat=41.9028,
        lng=12.4964,
        population=2873000,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="es-madrid",
        name="Madrid",
        country="Espanha",
        country_code="ESP",
        state="Comunidad de Madrid",
        state_code="MD",
        lat=40.4168,
        lng=-3.7038,
        population=3223000,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="pt-lisbon",
        name="Lisboa",
        country="Portugal",
        country_code="PRT",
        state="Lisboa",
        state_code="11",
        lat=38.7223,
        lng=-9.1393,
        population=506654,
        is_capital=True,
        continent="Europa",
    ),
    CityItem(
        id="eg-cairo",
        name="Cairo",
        country="Egito",
        country_code="EGY",
        state="Cairo",
        state_code="C",
        lat=30.0444,
        lng=31.2357,
        population=9540000,
        is_capital=True,
        continent="África",
    ),
    CityItem(
        id="au-sydney",
        name="Sydney",
        country="Austrália",
        country_code="AUS",
        state="New South Wales",
        state_code="NSW",
        lat=-33.8688,
        lng=151.2093,
        population=5312000,
        is_capital=False,
        continent="Oceania",
    ),
    # América do Sul adicional
    CityItem(
        id="uy-montevideo",
        name="Montevidéu",
        country="Uruguai",
        country_code="URY",
        state="Montevideo",
        state_code="MO",
        lat=-34.9011,
        lng=-56.1645,
        population=1319108,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="py-asuncion",
        name="Assunção",
        country="Paraguai",
        country_code="PRY",
        state="Distrito Capital",
        state_code="ASU",
        lat=-25.2637,
        lng=-57.5759,
        population=521559,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="bo-lapaz",
        name="La Paz",
        country="Bolívia",
        country_code="BOL",
        state="La Paz",
        state_code="LP",
        lat=-16.5000,
        lng=-68.1500,
        population=816044,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="bo-santacruz",
        name="Santa Cruz de la Sierra",
        country="Bolívia",
        country_code="BOL",
        state="Santa Cruz",
        state_code="SC",
        lat=-17.7833,
        lng=-63.1821,
        population=1453549,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="pe-lima",
        name="Lima",
        country="Peru",
        country_code="PER",
        state="Lima",
        state_code="LIM",
        lat=-12.0464,
        lng=-77.0428,
        population=9745517,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="pe-cusco",
        name="Cusco",
        country="Peru",
        country_code="PER",
        state="Cusco",
        state_code="CUS",
        lat=-13.5319,
        lng=-71.9675,
        population=428450,
        is_capital=False,
        continent="América do Sul",
    ),
    CityItem(
        id="co-bogota",
        name="Bogotá",
        country="Colômbia",
        country_code="COL",
        state="Cundinamarca",
        state_code="DC",
        lat=4.7110,
        lng=-74.0721,
        population=7743955,
        is_capital=True,
        continent="América do Sul",
    ),
    CityItem(
        id="co-medellin",
        name="Medellín",
        country="Colômbia",
        country_code="COL",
        state="Antioquia",
        state_code="ANT",
        lat=6.2442,
        lng=-75.5812,
        population=2569007,
        is_capital=False,
        continent="América do Sul",
    ),
    # América do Norte adicional
    CityItem(
        id="ca-toronto",
        name="Toronto",
        country="Canadá",
        country_code="CAN",
        state="Ontario",
        state_code="ON",
        lat=43.6532,
        lng=-79.3832,
        population=2794356,
        is_capital=False,
        continent="América do Norte",
    ),
    CityItem(
        id="ca-vancouver",
        name="Vancouver",
        country="Canadá",
        country_code="CAN",
        state="British Columbia",
        state_code="BC",
        lat=49.2827,
        lng=-123.1207,
        population=675218,
        is_capital=False,
        continent="América do Norte",
    ),
    CityItem(
        id="mx-mexicocity",
        name="Cidade do México",
        country="México",
        country_code="MEX",
        state="Ciudad de México",
        state_code="CDMX",
        lat=19.4326,
        lng=-99.1332,
        population=9209944,
        is_capital=True,
        continent="América do Norte",
    ),
    CityItem(
        id="mx-guadalajara",
        name="Guadalajara",
        country="México",
        country_code="MEX",
        state="Jalisco",
        state_code="JAL",
        lat=20.6597,
        lng=-103.3496,
        population=1460149,
        is_capital=False,
        continent="América do Norte",
    ),
]
